SET SERVEROUTPUT ON;
SET VERIFY OFF;

ACCEPT S_CITY_NAME PROMPT 'Enter the Departure City Name: ';

DECLARE
   V_CITY_NAME CITY.CITY_NAME%TYPE := '&S_CITY_NAME';
BEGIN
   ListOfFlights(V_CITY_NAME);
END;