CREATE OR REPLACE PROCEDURE NbOfPlanesPerCity(P_CITY_NAME IN CITY.CITY_NAME%TYPE, P_COUNT out number, P_FLAG OUT VARCHAR2)
IS
V_CITY_NAME CITY.CITY_NAME%TYPE;
BEGIN

    SELECT CITY_NAME
    INTO V_CITY_NAME
    FROM CITY
    WHERE UPPER(CITY_NAME) = UPPER(P_CITY_NAME);

   SELECT COUNT(*)
   INTO P_COUNT
   FROM PLANE, CITY
   WHERE PLANE.CITY_ID = CITY.CITY_ID
   AND UPPER(CITY.CITY_NAME) = UPPER(P_CITY_NAME);
   P_FLAG := 'YES';

EXCEPTION
   WHEN NO_DATA_FOUND THEN
    P_FLAG := 'NO';
END;